server:
    port: 8080
    servlet:
        context-path: /bookingflight
spring:
    datasource:
        url: "jdbc:mysql://localhost:3306/bookingflight"
        username: root
        password: 123456
    jpa:
        hibernate:
            ddl-auto: update
    ##tu dong tao bang neu chua co
jwt:
    signerKey: "BfwinYQq0J+dbjiORm97UyItmDO1XP8H20oGZPY2bam1A1AI1qcbmNsB03VtRpsY"